export default {
  ACCESS_TOKEN_STORE_KEY: '_NA_ACCESS_TOK',
  REFRESH_TOKEN_STORE_KEY: '_NA_REFRESH_TOK',
  DEVICE_ID_STORE_KEY: '_NA_DEVICE_ID',
  DARK_MODE_STORE_KEY: '_NA_IS_DARK_MODE',
  LAST_BACKGROUND_MODE_VALUE: '_NA_LAST_BACKGROUND_MODE_VALUE',
  LAST_THINKING_MODE_VALUE: '_NA_LAST_THINKING_MODE_VALUE',
  // Model override keys
  OVERRIDE_MODEL_TYPE_STORE_KEY: '_NA_OVERRIDE_MODEL_TYPE',
  OVERRIDE_MODEL_ID_STORE_KEY: '_NA_OVERRIDE_MODEL_ID',
  OVERRIDE_PLANNER_MODEL_TYPE_STORE_KEY: '_NA_OVERRIDE_PLANNER_MODEL_TYPE',
  OVERRIDE_PLANNER_MODEL_ID_STORE_KEY: '_NA_OVERRIDE_PLANNER_MODEL_ID',
  // Screenshot preferences
  SCREENSHOT_MEDIA_TYPE_STORE_KEY: '_NA_SCREENSHOT_MEDIA_TYPE', // e.g., image/jpeg, image/png
  SCREENSHOT_JPEG_QUALITY_STORE_KEY: '_NA_SCREENSHOT_JPEG_QUALITY', // 1-95
};